name: PR summary
on:
  pull_request:
    types:
      - "opened"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Use Node
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Install node dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Run PR summary action
      uses: ./ # Uses an action in the root directory
      with:
        OPENAI_API_KEY:  ${{ secrets.OPENAI_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
